### ISSUE TITLE
Resolver final-newline not working

### ISSUE THREAD

**Issue by rodrigomata** [srowhani/sass-lint-auto-fix#17]
## Problem Description

After trying to update the resolvers with a property from the [list](https://github.com/sasstools/sass-lint/tree/develop/docs/rules), the property `final-newline: 1` is not working.

## Screenshot

![screen shot 2018-05-08 at 3 15 47 pm](https://user-images.githubusercontent.com/15259836/39780923-61892c38-52d3-11e8-9dda-2e03a41178c8.png)

## Steps to recreate

- Add `final-newline: 1` under `resolvers` in .sass-lint.yml
- Run `sass-lint-auto-fix -c .sass-lint.yml -v`

**Comment by srowhani** [comment]
Thank you for bringing this to my attention. The final-newline resolver hasn't been implemented yet - more resolvers will be added over time.

In the meantime, I'll look into gracefully handling the case where a resolver doesn't exist.
