### ISSUE TITLE
Important being stripped by default, can break code.

### ISSUE THREAD

**Issue by webbertakken** [srowhani/sass-lint-auto-fix#32]
## Problem Description

The default configuration is too aggressive. It can break things.

Specifically the resolver `no-important` is set to `1` by default. Which makes it little desirable to have it under a pre-commit hook.

## Steps to reproduce

- Run sass-lint-auto-fix without a configuration, having a file that uses important.
- Notice the important simply being stripped, which in most cases would break code.

## Desired behaviour

Trust on default rules to not break your code.

I can make a PR if you please.

**Comment by srowhani** [comment]
I agree, I can see this being an issue. I'd gladly accept a PR if you open one.

**Comment by webbertakken** [comment]
I think this is all there is to it, or am i missing something? Please check for completeness.

**Comment by srowhani** [comment]
That's it, thanks for the contribution 🎉 . It may not cause a version bump because of the commit message, but I'll get a new version published 👍

**Comment by webbertakken** [comment]
Great!

Do you have a good source to read up on this version bump by commit message? I've not used it before.

**Comment by srowhani** [comment]
Oh yes! I use semantic versioning to bump the versions, and husky + commitlint to lint the commit messages.
