### ISSUE TITLE
Command files in Docker container

### ISSUE THREAD

**Issue by robbymarston** [srowhani/sass-lint-auto-fix#34]
## Problem Description

I get a generic `error Command failed with exit code 1.` error when running `sass-lint-auto-fix` inside a Docker container. Immediately proceeding the error is this (content redacted for readability):

```
@fix      Running resolver "property-sort-order" on "path/to/file.scss"
@write    Writing resolved tree to path/to/file.scss
{ details: 
   { file: 
      { filename: 'path/to/file.scss',
        content: 'SCSS CONTENT',
        options: [Object] } } }
```

If I re-run the command, it writes the file in question just fine but proceeds to error-out on another file. After re-running a total of 5 times, I get a `Done in 13.65s.` message and all files are fixed. The files in question appear to be valid save for a few sass-lint complaints. That said, I'm wondering if this is a memory issue i.e. there isn't enough memory to process larger files?

**Comment by srowhani** [comment]
I'll push out a patch tomorrow for more verbose logging and error reporting, and see if we can work from there.

Not too sure why it's ending early, I'd need more info.

**Comment by srowhani** [comment]
@robbymarston A new version will be published to provide more verbose logging around errors processing files. Try to see if you can trigger the error again on the new version.

**Comment by robbymarston** [comment]
Thank you @srowhani! Is the new version available now?

**Comment by srowhani** [comment]
I pushed a change to hopefully resolve this one out. Let me know if you're still getting that.

Thanks!

**Comment by srowhani** [comment]
This shouldn't be an issue anymore. If it continues to persist, please reopen. Thanks!
