### ISSUE TITLE
Cannot read property 'is' of undefined, no other info

### ISSUE THREAD

**Issue by Johanneke** [srowhani/sass-lint-auto-fix#38]
## Problem Description

I get *loads* of the error message `Cannot read property 'is' of undefined`, without an further logging. So I have no clue what is going on here.

## Screenshot

<img width="364" alt="screen shot 2018-08-29 at 18 44 14" src="https://user-images.githubusercontent.com/5793090/44802334-b8a73500-abbb-11e8-8825-c79616ae421d.png">

## Steps to recreate

- .sass-lint.yml without rules
- run sass-lint-auto-fix

**Comment by Johanneke** [comment]
Lots of debugging shows me it's `final-newline` that is the problem. I see there is already another issue open for that.

I do have the `final-newline` rule disabled in both sass-lint and sass-lint-auto-fix, so it would be nice if it didn't result in an error. Seems like files are put throught `sass-lint` by this library, even if the rule is disabled.

**Comment by Johanneke** [comment]
I've had a look. The reason that the rule is not skipped, even though it is disabled in my `.sass-lint.yml` config, is because `sass-lint-auto-fix` has no option to pass my custom `sass-lint` config. As a result, the default from `node-modules` is used...

**Comment by srowhani** [comment]
I see. That'll definitely be an available configuration option in the future, and also just resolving the correct sass-lint.yml file. Thanks for digging into this.
