### ISSUE TITLE
Rule: no-color-keywords. Mistake after fix.

### ISSUE THREAD

**Issue by georgelviv** [srowhani/sass-lint-auto-fix#56]
## Problem Description

Rule: no-color-keywords. Mistake after fix.
Input:
background: olivedrab;
Expected:
background: #6b8e23
Actual:
background: #6b8e23drab;

## Screenshot

![image](https://user-images.githubusercontent.com/9251831/46610897-c03fef00-cb14-11e8-92fe-5faee1b18b07.png)

**Comment by srowhani** [comment]
Good catch! Thanks for reporting it.
