### ISSUE TITLE
version 0.2.7 does not contain the fix for `files.ignore`

### ISSUE THREAD

**Issue by kinyat** [srowhani/sass-lint-auto-fix#6]
## Problem Description
It seems the built files are not included the fix for files.ignore

## Screenshot

![image](https://user-images.githubusercontent.com/1476974/38844195-b9679768-4235-11e8-9513-c4dcadfa8b70.png)

![image](https://user-images.githubusercontent.com/1476974/38844112-63db5730-4235-11e8-8712-adef01c4fd64.png)

## Steps to recreate

update to v0.2.7

**Comment by srowhani** [comment]
Published as 0.2.8 - I need to set up travis to do the releases 😅
