### ISSUE TITLE
Remove package dependency on git.

### ISSUE THREAD

**Issue by insensitive** [srowhani/sass-lint-auto-fix#61]
### Remove package dependency on git. It creates problem where buildsystem does not support git and supports only npm packages.

Currently package depends on gonzales-pe-sl through a git url. Can we change that and mention package version ^4.2.3 as done in sass-lint package.

<img width="394" alt="screen shot 2018-10-17 at 2 56 06 pm" src="https://user-images.githubusercontent.com/1289075/47076644-ccb2fe80-d21c-11e8-87cc-a51bf24185d5.png">

Let me know if this exists for some reason. 
I can raise a PR if this makes sense.

Thanks for the wonderful tool.

**Comment by srowhani** [comment]
Thanks for reporting this, but unfortunately it can't be switched. My fork adds a safeguard that if not there would cause frequent errors. I'd be happy to merge into sass-lint's gonzales fork, but I don't think the org is particularly active.

If you're worried about dependencies getting ambiguous, you can install sass-lint-auto-fix globally.

**Comment by tonyganch** [comment]
Hey @srowhani, please create a PR and someone please ping me on twitter?
I'll take a look and merge it.
