### ISSUE TITLE
Do not initialize sentry if optOut is set

### ISSUE THREAD

**Issue by sascha-egerer** [srowhani/sass-lint-auto-fix#63]
## Problem Description

Sentry should not be initialized or loaded at all if `optOut` is set to `true`

**Comment by sascha-egerer** [comment]
This issue was about to disable the whole initialize / loading of the sentry module. Requiering the file should IMO be based on this option.

**Comment by srowhani** [comment]
This is now resolved in v0.18.0 🎉
