### ISSUE TITLE
Preserve sass-lint directive comment positions

### ISSUE THREAD

**Issue by benelliott** [srowhani/sass-lint-auto-fix#75]
## Problem Description

When a comment is used to disable linting for a particular rule (e.g. `// sass-lint:disable-line rule-name`) and the fixer rearranges the rule to obey the `property-sort-order` lint config, the comment stays where it was. This can cause lint errors because the ignore directive is no longer being applied to the correct line.

**Comment by srowhani** [comment]
Sorry, just noticed this now. I'll look into this tonight.

Thanks for reporting.
