### ISSUE TITLE
Cannot checkout repository on windows

### ISSUE THREAD

**Issue by Kyusung4698** [srowhani/sass-lint-auto-fix#82]
## Problem Description

I cannot checkout this repository as windows does not allow an * in file names. 

## Screenshot

`Cloning into 'C:\Projects\sass-lint-auto-fix'...
error: unable to create file test/sample-config/config.*: Invalid argument
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
`

## Steps to recreate

Clone repository on windows.

**Comment by srowhani** [comment]
Thanks for bringing this to my attention. I've added appveyor to make sure that it works on windows as well.
