### ISSUE TITLE
No dist/ folder in npm packages for v0.17.0

### ISSUE THREAD

**Issue by nitinkumar8553** [srowhani/sass-lint-auto-fix#97]
## Problem Description
I'm trying to install sass-lint-auto-fix in my mac by running below command
npm install --save-dev sass-lint-auto-fix and getting below error

347 verbose stack Error: ENOENT: no such file or directory, chmod '/Users/nitinkpathak/Desktop/repo/client/node_modules/sass-lint-auto-fix/dist/index.js'
348 verbose cwd /Users/nitinkpathak/Desktop/repo/client
349 verbose Darwin 18.0.0
350 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "--save-dev" "sass-lint-auto-fix"
351 verbose node v10.16.3
352 verbose npm  v6.9.0
353 error path /Users/nitinkpathak/Desktop/repo/client/node_modules/sass-lint-auto-fix/dist/index.js
354 error code ENOENT
355 error errno -2
356 error syscall chmod
357 error enoent ENOENT: no such file or directory, chmod '/Users/nitinkpathak/Desktop/repo/nfv-ng-ui/node_modules/client/dist/index.js'
358 error enoent This is related to npm not being able to find a file.
359 verbose exit [ -2, true ]

Guess we already have the same issue with different version-
https://github.com/srowhani/sass-lint-auto-fix/issues/7
Please let me know if anything wrong from my side.

**Comment by srowhani** [comment]
I'm not able to reproduce. Can you confirm if it's just the dist/ directory missing?

**Comment by deepanrajkumar** [comment]
The same issue happens if we remove the node_modules and, do npm install. Just do npm i error is thrown.

Tested in 10.16.3 and 8.16.2 issue in both version.

`npm ERR! path /Users/username/repo/node_modules/sass-lint-auto-fix/dist/index.js
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall chmod
npm ERR! enoent This is related to npm not being able to find a file.`

**Comment by nitinkumar8553** [comment]
I've already tried this but still getting the same error. 
I removed the it from my package.json and delete the folder for sass-list-auto-fix but no luck

**Comment by nitinkumar8553** [comment]
npm ERR! path /Users/nitinkpathak/Desktop/repo/ng-ui/node_modules/sass-lint-auto-fix/dist/index.js
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall chmod
npm ERR! enoent ENOENT: no such file or directory, chmod '/Users/nitinkpathak/Desktop/repo/ng-ui/node_modules/sass-lint-auto-fix/dist/index.js'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/nitinkpathak/.npm/_logs/2019-10-14T16_27_03_004Z-debug.log

**Comment by nitinkumar8553** [comment]
one more doubt I want to clear with you guys, should sass-lint-auto-fix be part of Devdependencies or dependencies, and is there any peer dependencies for sass-lint-auto-fix.

**Comment by nitinkumar8553** [comment]
> I'm not able to reproduce. Can you confirm if it's just the dist/ directory missing?

> **below lines are from the log file when I executed npm install**

347 verbose stack Error: ENOENT: no such file or directory, chmod '/Users/nitinkpathak/Desktop/repo/nfv-ng-ui/node_modules/sass-lint-auto-fix/dist/index.js'
348 verbose cwd /Users/nitinkpathak/Desktop/repo/nfv-ng-ui
349 verbose Darwin 18.0.0
350 verbose argv "/Users/nitinkpathak/.nvm/versions/node/v10.16.3/bin/node" "/Users/nitinkpathak/.nvm/versions/node/v10.16.3/bin/npm" "install" "sass-lint-auto-fix"
**351 verbose node v10.16.3
352 verbose npm  v6.9.0**
353 error path /Users/nitinkpathak/Desktop/repo/ng-ui/node_modules/sass-lint-auto-fix/dist/index.js
354 error code ENOENT
355 error errno -2
356 error syscall chmod
357 error enoent ENOENT: no such file or directory, chmod '/Users/nitinkpathak/Desktop/repo/ng-ui/node_modules/sass-lint-auto-fix/dist/index.js'
358 error enoent This is related to npm not being able to find a file.
359 verbose exit [ -2, true ]


after that, I deleted my project node-modules and remove the sass-lint-auto-fix from package.json
and did  npm install and then tried installing sass-lint-auto-fix explicitly by running below command

npm install sass-lint-auto-fix

npm ERR! path /Users/nitinkpathak/Desktop/repo/ng-ui/node_modules/sass-lint-auto-fix/dist/index.js
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall chmod
npm ERR! enoent ENOENT: no such file or directory, chmod '/Users/nitinkpathak/Desktop/repo/ng-ui/node_modules/sass-lint-auto-fix/dist/index.js'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/nitinkpathak/.npm/_logs/2019-10-14T16_27_03_004Z-debug.log

**Comment by aerze** [comment]
Hello, I'm having the same issue with the latests published version v0.18.0.
My team uses Proximity as a proxy npm server, not sure if that affects anything.

```sh
npm ERR! path /Users/g0s027f/.npm/_npx/13033/lib/node_modules/sass-lint-auto-fix/dist/index.js
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall chmod
npm ERR! enoent ENOENT: no such file or directory, chmod '/Users/g0s027f/.npm/_npx/13033/lib/node_modules/sass-lint-auto-fix/dist/index.js'
npm ERR! enoent This is related to npm not being able to find a file.
```

**Comment by srowhani** [comment]
For the time being I suggest reverting to 0.17.0. There appears to have been some build related issues since the most recent changes that CI hadn't picked up on.

@nitinkumar8553 In your package.json can you explicitly set the version, and let me know if that works for you. I have no problems running the version you mentioned, so I'm interested to see what's going wrong.

Please paste the entry in the package.json, or the mentioned version in your package-lock, or yarn.lock file.

@nitinkumar8553 It should be part of dev dependencies, you are correct. It should work either way though.

**Comment by nitinkumar8553** [comment]
@srowhani finally able to install it without any issue with the dist folder as well.

earlier in my package.json, I've given the version number with caret ^ but this time added without ^ or ~.

**Comment by stevensacks** [comment]
I'm having this issue with 0.18.0. I've uninstall/reinstalled numerous times. I've deleted my yarn.lock and node_modules, etc.

Solution for me was to explicitly install 0.17.0.

```
yarn add -D sass-lint-auto-fix@0.17.0
```

**Comment by srowhani** [comment]
@nitinkumar8553 let's leave it open. I'll publish a new version to resolve any build issues with the current one.

**Comment by keonik** [comment]
Hello, Looking back, 0.17.1 had this issue as well. The only commits that I saw touching the dist folder or build script was 10 days ago changing build scripts to run using yarn instead of npm. Has anyone looked at that yet?

**Comment by Zialus** [comment]
@srowhani any ETA for the new version?

**Comment by srowhani** [comment]
Published a new version that builds correctly. Will have to resolve some issues with semantic release, but this should do in the meantime.

Sorry for any inconveniences!

**Comment by srowhani** [comment]
Build is now working as expected. Please reopen if issue persists.
